name: morph-kgc

morph_kgc_config: config/config.ini
configmap_config: configmap-config
configmap_mappings: configmap-mappings

image:
  repository: morph-kgc
  tag: latest
  pullPolicy: Always

cronJob:
  enabled: false
  schedule: "* * * * *"

